routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layout');
});
//home login
Route::get('/admin','HomeController@index')->name('admin.index');

Route::post('/postLogin','HomeController@postLogin')->name('admin.postLogin');


Route::group(['prefix'=>'admin','as'=>'admin.','middleware' => 'checkLogin'], function(){



    Route::resource('/user','UserController');
    Route::resource('/slide','SlideController');
    Route::resource('/brand','BrandProductController');
    Route::resource('/product','ProductController');
    Route::resource('/category','CategoryController');
    Route::resource('/coupon','CouponController');

});

//frontend
//trang - chu
Route::get('/trang-chu','ShopController@index')->name('index');


Route::get('/category','ShopController@index')->name('category.index');
Route::get('/brand/{brand_slug}','ShopController@index')->name('brand.brand_slug');


Route::get('/category/{slug_category_product}','ShopController@show_category')->name('show_category');

Route::get('/trang-chu/chi-tiet/{product_id}','ShopController@detail_product')->name('product.detail');

Route::get('/danh-muc','ShopController@category')->name('home.category');
Route::get('/lien-he','ShopController@contact')->name('contact');
Route::get('/lien-he-voi-chung-toi','ShopController@postContact')->name('post.contact');

//shopping cart

Route::get('gio-hang','CartController@index')->name('cart.index');
Route::get('gio-hang/them-san-pham-gio-hang/{product_id}','CartController@addCart')->name('cart.add');
Route::delete('gio-hang/xoa-san-pham/{rowId}','CartController@removeCart')->name('cart.destroy');
Route::post('gio-hang/cap-nhap-gio-hang/','CartController@updateCart')->name('cart.update');
Route::get('gio-hang/tinh-ma-giam-gia','CartController@check_coupon')->name('check.coupon');

Route::post('gio-hang/cap-nhap-san-pham/','CartController@updateCart')->name('updateCart');

//Route::get('giohang','CartController@test')->name('cart');

app/Brand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    public $timestamps = false;
    protected $table = 'tbl_brand';
    protected $primaryKey = 'brand_id';
    protected $fillable =[
        'brand_name','brand_slug','brand_desc','brand_status','created_at','updated_at'
    ];
    public function Products() {
        return $this->hasMany('App\Product');
    }
}

resources/views/backend/brand/create.blade.php
@extends('backend.layout.main')
@section('content')
<div class="content-wrapper">

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Thêm NCC <a href="{{route('admin.brand.index')}}" class="btn bg-purple "><i class="fa fa-plus"></i> Danh sách NCC</a>

      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#"> BRAND </a></li>

      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">

        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Nhập thông tin NCC</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->

            <form role="form" action = "{{route('admin.brand.store')}}" method = "post" enctype="multipart/form-data">
            @csrf
              <div class="box-body">
            <div class="col-md-6">

              <div class="form-group">
                  <label for="exampleInputEmail1">brand_name</label>
                  <input data-validation="required"  data-validation-error-msg ="Điền tên nhà cung cấp có ít nhất 1 ký tự"
                   type="text" class="form-control" name="brand_name" id="brand_name"
                   placeholder="Enter brand_name">

                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">brand_slug</label>
                    <input class="form-control" type="text" id="brand_slug" name="brand_slug" >


                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">brand_desc </label>
                  <textarea   rows="3" class="form-control" name ="brand_desc"
                  id="brand_desc" placeholder="Enter brand_desc"></textarea>

                </div>
                <div class="form-group">
                  <label for="exampleInputPassword1">brand_status</label>
                  <input type="number" class="form-control" name ="brand_status" id="brand_status" placeholder="Enter brand_status">
                  @if($errors->has('brand_status'))
                  <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px;color:red" >
                              <i class="fa fa-info"></i>{{$errors->first('brand_status')}}
                    </label>
                  @endif
                </div>



                <div class="checkbox">
                  <label>
                    <input type="checkbox"> Check me out
                  </label>
                </div>
              </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
          <!-- /.box -->
        </div>
      </div>

    </section>
    <!-- /.content -->
  </div>
@endsection
@section('scripts')
<script type="text/javascript">


    $('#brand_name').keyup(function(event) {


    var title, slug;

    //Lấy text từ thẻ input title
    title = document.getElementById("brand_name").value;

    //Đổi chữ hoa thành chữ thường
    slug = title.toLowerCase();

    //Đổi ký tự có dấu thành không dấu
    slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
    slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
    slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
    slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
    slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
    slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
    slug = slug.replace(/đ/gi, 'd');
    //Xóa các ký tự đặt biệt
    slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
    //Đổi khoảng trắng thành ký tự gạch ngang
    slug = slug.replace(/ /gi, " - ");
    //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
    //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
    slug = slug.replace(/\-\-\-\-\-/gi, '-');
    slug = slug.replace(/\-\-\-\-/gi, '-');
    slug = slug.replace(/\-\-\-/gi, '-');
    slug = slug.replace(/\-\-/gi, '-');
    //Xóa các ký tự gạch ngang ở đầu và cuối
    slug = '@' + slug + '@';
    slug = slug.replace(/\@\-|\-\@|\@/gi, '');
    //In slug ra textbox có id “slug”
    $('#brand_slug').val(slug);

});
</script>
<script type="text/javascript" src="backend/ckeditor/ckeditor.js"></script>
<script type="text/javascript">
    $(function () {
        CKEDITOR.replace('ckeditor');
        CKEDITOR.config.pasteFormWordPromptCleanup = true;
        CKEDITOR.config.pasteFormWordRemoveFontStyles = false;
        CKEDITOR.config.pasteFormWordRemoveStyles = false;
        CKEDITOR.config.language = 'vi';
        CKEDITOR.config.htmlEncodeOutput = false;
        CKEDITOR.config.ProcessHTMLEntities = false;
        CKEDITOR.config.entities = false;
        CKEDITOR.config.entities_latin = false;
        CKEDITOR.config.ForceSimpleAmpersand = true;
        CKEDITOR.replace('brand_desc');
    });
</script>
@endsection

resources/views/backend/brand/edit.blade.php
@extends('backend.layout.main')
@section('content')
<div class="content-wrapper">

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Sửa NCC <a href="{{route('admin.brand.index')}}" class="btn bg-purple "><i class="fa fa-plus"></i> Danh sách NCC</a>
        
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#"> BRAND </a></li>
        
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Sửa thông tin NCC</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            
            <form role="form" action = "{{route('admin.brand.update',['brand'=>$brand->brand_id])}}" method = "post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
              <div class="box-body">
            <div class="col-md-6">
             
              <div class="form-group">
                  <label for="exampleInputEmail1">New brand_name</label>
                  <input data-validation="required"  data-validation-error-msg ="Điền tên nhà cung cấp có ít nhất 1 ký tự"
                   type="text" class="form-control" name="brand_name" id="brand_name" 
                   placeholder="Enter brand_name" value="{{$brand->brand_name}}">
                  
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">New brand_slug</label>
                    <input class="form-control" type="text" id="brand_slug" name="brand_slug" value="{{$brand->brand_slug}}" >

                  
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1"> New brand_desc </label>
                  <textarea type ="text"  rows="3" class="form-control" name ="brand_desc" 
                  id="brand_desc" placeholder="Enter brand_desc" > </textarea>
                  
                </div>
                <div class="form-group">
                  <label for="exampleInputPassword1">New brand_status</label>
                  <input type="number" class="form-control" name ="brand_status" id="brand_status" placeholder="Enter brand_status" value="{{$brand->brand_status}}">
                  
                </div>

                
                
                <div class="checkbox">
                  <label>
                    <input type="checkbox"> Check me out
                  </label>
                </div>
              </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Update</button>
              </div>
            </form>
          </div>
          <!-- /.box -->
        </div>
      </div>
      
    </section>
    <!-- /.content -->
  </div>
@endsection
@section('scripts')
<script type="text/javascript">
    

    $('#brand_name').keyup(function(event) {

    
    var title, slug;
 
    //Lấy text từ thẻ input title 
    title = document.getElementById("brand_name").value;
 
    //Đổi chữ hoa thành chữ thường
    slug = title.toLowerCase();
 
    //Đổi ký tự có dấu thành không dấu
    slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
    slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
    slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
    slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
    slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
    slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
    slug = slug.replace(/đ/gi, 'd');
    //Xóa các ký tự đặt biệt
    slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
    //Đổi khoảng trắng thành ký tự gạch ngang
    slug = slug.replace(/ /gi, " - ");
    //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
    //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
    slug = slug.replace(/\-\-\-\-\-/gi, '-');
    slug = slug.replace(/\-\-\-\-/gi, '-');
    slug = slug.replace(/\-\-\-/gi, '-');
    slug = slug.replace(/\-\-/gi, '-');
    //Xóa các ký tự gạch ngang ở đầu và cuối
    slug = '@' + slug + '@';
    slug = slug.replace(/\@\-|\-\@|\@/gi, '');
    //In slug ra textbox có id “slug”
    $('#brand_slug').val(slug);

});
</script>

@endsection

resources/views/backend/brand/index.blade.php
@extends('backend.layout.main')
@section('content')
<div class="content-wrapper">

    <section class="content-header">
      <h1>
        DANH SÁCH QUẢN LÝ NHÀ CUNG CẤP <a href="{{route('admin.brand.create')}}" class="btn bg-purple btn-flat"><i class="fa fa-plus"></i> Thêm NCC</a>

      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-user"></i> QUẢN LÝ BRAND </a></li>
      </ol>
    </section>

<section class="content">

     <div class="row">
       <div class="col-md-12">
         <div class="box">

            <div class="box-header with-border">

              <h3 class="box-title">Danh Sách BRAND</h3>

            </div>
            @if(session()->has('success'))
              <div class="alert alert-success">{{session()->get('success')}}</div>
            @endif


            <div class="box-body">
                <table class="table table-border">
                  <tbody>
                            <tr>
                                <th style="width: 10px">STT</th>
                                <th>brand_name</th>
                                <th>brand_slug</th>
                                <th>brand_desc</th>
                                <th>brand_status</th>
                                <th>created_at</th>
                                <th>Hành Động</th>
                            </tr>
                          @foreach($data as $key => $item)
                            <tr class="item-{{ $item->id }}">
                                <td>{{ $key +1}}</td>
                                <td>{{ $item->brand_name }}</td>
                                <td>{{ $item->brand_slug }}</td>
                                <td>{{ strip_tags($item->brand_desc,) }}</td>
                                <td>{{ $item->brand_status }}</td>
                                <td>{{ $item->created_at }}</td>

                                <td>
                                   <a  href="{{route('admin.brand.edit',['brand'=>$item->brand_id])}}" class="btn btn-warning btn-edit"><i class="fa fa-pencil"></i></a>
                                   <button data-id="{{$item->brand_id}}" class="btn btn-danger btn-delete"><i class="fa fa-trash"></i></button>
                                </td>
                            </tr>
                          @endforeach
                  </tbody>
                </table>
            </div>
            <div class="box-footer clearfix">
                        {{ $data->links() }}
                    </div>
         </div>
       </div>

     </div>


    </section>
@endsection
@section('my_js')
<script type="text/javascript">
        $(document).ready(function() {
            // Thiết lập csrf => chổng giả mạo
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN' : $('meta[name="csrf-token"]').attr('content')
                }
            })

            $('.btn-delete').on('click',function () {

                let id = $(this).data('id');

                let result = confirm("Bạn có chắc chắn muốn xóa ?");

                if (result) { // neu nhấn == ok , sẽ send request ajax

                    $.ajax({
                        url: '/admin/brand/'+id, // http://webthucpham.local:8888/user/8
                        type: 'DELETE', // phương truyền tải dữ liệu
                        data: {
                            // dữ liệu truyền sang nếu có
                            name : 'dung'
                        },
                        dataType: "json", // kiểu dữ liệu muốn nhận về
                        success: function (res) {

                            if (res.success != 'undefined' && res.success == 1) { // xóa thành công
                                $('.item-'+id).remove();
                            }
                            window.location.href = '/admin/brand';
                        },
                        error: function (e) { // lỗi nếu có
                            console.log(e);
                        }
                    });
                }

            });

            /*$( ".btn-delete" ).click(function() {
                alert( "Handler for .click() called." );
            });*/

        });
    </script>
@endsection