routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layout');
});
//home login
Route::get('/admin','HomeController@index')->name('admin.index');

Route::post('/postLogin','HomeController@postLogin')->name('admin.postLogin');


Route::group(['prefix'=>'admin','as'=>'admin.','middleware' => 'checkLogin'], function(){



    Route::resource('/user','UserController');
    Route::resource('/slide','SlideController');
    Route::resource('/brand','BrandProductController');
    Route::resource('/product','ProductController');
    Route::resource('/category','CategoryController');
    Route::resource('/coupon','CouponController');

});

//frontend
//trang - chu
Route::get('/trang-chu','ShopController@index')->name('index');


Route::get('/category','ShopController@index')->name('category.index');
Route::get('/brand/{brand_slug}','ShopController@index')->name('brand.brand_slug');


Route::get('/category/{slug_category_product}','ShopController@show_category')->name('show_category');

Route::get('/trang-chu/chi-tiet/{product_id}','ShopController@detail_product')->name('product.detail');

Route::get('/danh-muc','ShopController@category')->name('home.category');
Route::get('/lien-he','ShopController@contact')->name('contact');
Route::get('/lien-he-voi-chung-toi','ShopController@postContact')->name('post.contact');

//shopping cart

Route::get('gio-hang','CartController@index')->name('cart.index');
Route::get('gio-hang/them-san-pham-gio-hang/{product_id}','CartController@addCart')->name('cart.add');
Route::delete('gio-hang/xoa-san-pham/{rowId}','CartController@removeCart')->name('cart.destroy');
Route::post('gio-hang/cap-nhap-gio-hang/','CartController@updateCart')->name('cart.update');
Route::get('gio-hang/tinh-ma-giam-gia','CartController@check_coupon')->name('check.coupon');

Route::post('gio-hang/cap-nhap-san-pham/','CartController@updateCart')->name('updateCart');

//Route::get('giohang','CartController@test')->name('cart');

app/Brand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    public $timestamps = false;
    protected $table = 'tbl_brand';
    protected $primaryKey = 'brand_id';
    protected $fillable =[
        'brand_name','brand_slug','brand_desc','brand_status','created_at','updated_at'
    ];
    public function Products() {
        return $this->hasMany('App\Product');
    }
}

app/CategoryProduct.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class   CategoryProduct extends Model
{
    public $timestamps = false;
    protected $table = 'tbl_category_product';
    protected $primaryKey = 'category_id';
    protected $fillable =[
        'meta_keywords','category_name','slug_category_product','category_desc','category_status'
    ];

     public function Product()
    {

        return $this->hasMany('App\Product');
    }
}

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    public $timestamp = false;
    protected $fillable = [
        'name_city','type'
    ];
}

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    public $timestamps = false;
    protected $table = 'tbl_contacts';
    protected $fillable = ['name','phone','email','content','create_at'];
}

app/Coupon.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Coupon extends Model
{
    public $timestamps = false;
        protected $fillable = [
        'coupon_name','coupon_time','coupon_condition','coupon_number','coupon_code'
    ];
    protected $primaryKey= 'coupon_id';
    protected $table = 'tbl_coupon';
}

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    public $timestamp = false;
    protected $fillable = [
        'customer_name','customer_email','customer_password','customer_phone'
    ];
}

app/Freeship.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Freeship extends Model
{
    public $timestamp = false;
    protected $fillable = [
        'fee_matp','fee_maqh','fee_xaid','fee_feeship'
    ];
}

app/Login.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Login extends Model
{
    public $timestamp = false;
    protected $fillable = [
        'admin_email','admin_password','admin_name','admin_phone'
    ];
}

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    public $timestamp = false;
    protected $fillable = [
        'customer_id','shipping_id','order_status','order_code'
    ];
    public function product(){
        return $this->belongsToMany('App\Product');
    }
}

app/OrderDetails.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class OrderDetails extends Model
{
    public $timestamp = false;
    protected $fillable = [
        'order_code','product_id','product_name','product_price','product_sales_quantity','product_coupon',
        'product_feeship','created_at'
    ];
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public $timestamp = false;
    protected $table = 'tbl_product';
    protected $primaryKey = 'product_id';
    protected $fillable = [
            'product_name','product_quantity','product_slug','category_id','brand_id','product_desc','product_content',
        'product_price','product_image','product_status',
    ];

    public function category(){
        return $this->belongsTo('App\CategoryProduct','category_id');
    }
    public function Brand(){
        return $this->belongsTo('App\Brand','brand_id');
    }

    public function Order(){
        return $this->belongsToMany('App\Order','App\OrderDetails','product_id','order_code');
    }
}

app/Province.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Province extends Model
{
    public $timestamp = false;
    protected $fillable = [
        'name_quanhuyen','type','matp'
    ];
}

app/Roles.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Roles extends Model
{
    public $timestamps = false;
    protected $fillable = [
        'name'
    ];
    public function admin(){
        return $this->belongsTo('App\Admin');
    }
}

app/RolesUser.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class RolesUser extends Model
{
    //
}

app/Shipping.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Shipping extends Model
{
    public $timestamps = false; //set time to false
    protected $fillable = [
    	'shipping_name', 'shipping_address', 'shipping_phone','shipping_email','shipping_notes','shipping_method'
    ];
}

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    public $timestamps = false; //set time to false
    protected $table = 'tbl_slider';
    protected $primaryKey = "slider_id";
    protected $fillable = [
    	'slider_name', 'slider_image','slider_status','slider_desc'
    ];
}

app/Social.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Social extends Model
{
    public $timestamps = false;
    protected $fillable = [
          'provider_user_id',  'provider',  'user'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Wards.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Wards extends Model
{
    public $timestamps = false; //set time to false
    protected $fillable = [
    	'name_xaphuong', 'type', 'maqh'
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/backend/layout/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.4.18
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE</a>.</strong> All rights
    reserved.
  </footer>

resources/views/backend/layout/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b>LT</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Admin</b>LTE</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
         
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="/backend/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
              <span class="hidden-xs">Alexander Pierce</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="/backend/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">

                <p>
                  Alexander Pierce - Web Developer
                  <small>Member since Nov. 2012</small>
                </p>
              </li>
              <!-- Menu Body -->
              <li class="user-body">
                <div class="row">
                  <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                  </div>
                </div>
                <!-- /.row -->
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="#" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>
        </ul>
      </div>
    </nav>
  </header>

resources/views/backend/layout/main.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Dashboard</title>
    <base href="{{asset("")}}">
    <meta name="csrf-token" content="{{csrf_token()}}">

    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="backend/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="backend/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="backend/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="backend/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="backend/dist/css/skins/_all-skins.min.css">

    <!-- Daterange picker -->
    <link rel="stylesheet" href="backend/bower_components/bootstrap-daterangepicker/daterangepicker.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="backend/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

@include('backend.layout.header')


@include('backend.layout.sidebar')


@yield('content')
@include('backend.layout.footer')



<!-- jQuery 3 -->
    <script src="backend/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="backend/bower_components/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.7 -->
    <script src="backend/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- datepicker -->
    <script src="backend/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="backend/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
    <!-- Slimscroll -->
    <script src="backend/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="backend/bower_components/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="backend/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="backend/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="backend/dist/js/demo.js"></script>

    <script src="js/jquery.form-validator.min.js"></script>
    <script type="text/javascript">
        $.validate({});
    </script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@yield('my_js')
@yield('scripts')
</body>
</html>

resources/views/backend/layout/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="/backend/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>Alexander Pierce</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>

      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">

      <li class="active ">
          <a href="{{route('admin.slide.index')}}">
            <i class="fa fa-user"></i> <span >QUẢN LÝ SLIDE</span>
          </a>
        </li>
        <li class="active ">
          <a href="{{route('admin.user.index')}}">
            <i class="fa fa-user"></i> <span >QUẢN LÝ USER</span>
          </a>
        </li>
        <li class="active">
          <a href="{{route('admin.brand.index')}}">
            <i class="fa fa-list"></i> <span>QUẢN LÝ NCC</span>
          </a>
        </li>
        <li class="active">
          <a href="{{route('admin.category.index')}}">
            <i class="fa fa-list"></i> <span>QUẢN LÝ DANH MỤC</span>
          </a>
        </li>
          <li class="active">
              <a href="{{route('admin.product.index')}}">
                  <i class="fa fa-list"></i> <span>QUẢN LÝ SẢN PHẨM</span>
              </a>
          </li>
        <li class="active treeview">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>QUẢN LÝ TIN TỨC</span>
          </a>
        </li>

          <li class="active">
              <a href="{{route('admin.coupon.index')}}">
                  <i class="fa fa-list"></i> <span>QUẢN LÝ MÃ GIẢM GIÁ</span>
              </a>
          </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

resources/views/frontend/category.blade.php
@extends('frontend.layout')
@section('content')
    <section id="advertisement">
        <div class="container">
            <img src="/frontend/images/shop/advertisement.jpg" alt="" />
        </div>
    </section>

    <section>
        <div class="container">
            <div class="row">


                <div class="col-sm-12 padding-right">
                    <div class="features_items">
                        <h2 class="title text-center">Điện Thoại Apple</h2>
                        <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                @foreach($mobile as $key=>$mobile)
                                    @if($key % 3 == 0)
                                        <div class="item {{$key == 0 ? 'active' : '' }} ">
                                            @endif
                                            <div class="col-sm-4">
                                                <div class="product-image-wrapper">
                                                    <div class="single-products">
                                                        <div class="productinfo text-center">
                                                            <img src="/upload/product/{{$mobile->product_image}}" alt="" height="250px" />
                                                            <h2>{{number_format($mobile->product_price)}} VNĐ</h2>
                                                            <p>{{$mobile->product_name}}</p>
                                                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>

                                                        </div>

                                                    </div>
                                                </div>
                                                <div class="choose">
                                                    <ul class="nav nav-pills nav-justified">
                                                        <li><a href="{{route('product.detail',['product_id'=>$mobile->product_id])}}"><i class="fa fa-plus-square"></i>Chi Tiết</a></li>
                                                        <li><a href="#"><i class="fa fa-plus-square"></i>So sánh</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                            @if($key % 3 ==2)
                                        </div>
                                    @endif
                                @endforeach
                            </div>
                            <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                            </a>
                            <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>
                    </div>

                </div>

                <div class="col-sm-12 padding-right">
                    <div class="features_items">
                        <h2 class="title text-center" >Laptop Nổi Bật</h2>
                        <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                @foreach($laptop as $key=>$laptop)

                                        <div class="item active ">

                                            <div class="col-sm-4">
                                                <div class="product-image-wrapper">
                                                    <div class="single-products">
                                                        <div class="productinfo text-center">
                                                            <img src="/upload/product/{{$laptop->product_image}}" alt="" height="250px" />
                                                            <h2>{{number_format($laptop->product_price)}} VNĐ</h2>
                                                            <p>{{$laptop->product_name}}</p>
                                                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>

                                                        </div>

                                                    </div>
                                                </div>
                                                <div class="choose">
                                                    <ul class="nav nav-pills nav-justified">
                                                        <li><a href="{{route('product.detail',['product_id'=>$laptop->product_id])}}"><i class="fa fa-plus-square"></i>Chi Tiết</a></li>
                                                        <li><a href="#"><i class="fa fa-plus-square"></i>So sánh</a></li>
                                                    </ul>
                                                </div>
                                            </div>

                                        </div>

                                @endforeach
                            </div>

                        </div>

                        <h2 class="title text-center" >Ngành Thời Trang Nam</h2>
                        <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                @foreach($thoitrangnam as $key=>$thoitrangnam)

                                    <div class="item active ">

                                        <div class="col-sm-4">
                                            <div class="product-image-wrapper">
                                                <div class="single-products">
                                                    <div class="productinfo text-center">
                                                        <img src="/upload/product/{{$thoitrangnam->product_image}}" alt="" height="300px" />
                                                        <h2>{{number_format($thoitrangnam->product_price)}} VNĐ</h2>
                                                        <p>{{$thoitrangnam->product_name}}</p>
                                                        <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>

                                                    </div>

                                                </div>
                                            </div>
                                            <div class="choose">
                                                <ul class="nav nav-pills nav-justified">
                                                    <li><a href="{{route('product.detail',['product_id'=>$thoitrangnam->product_id])}}"><i class="fa fa-plus-square"></i>Chi Tiết</a></li>
                                                    <li><a href="#"><i class="fa fa-plus-square"></i>So sánh</a></li>
                                                </ul>
                                            </div>
                                        </div>

                                    </div>

                                @endforeach
                            </div>

                        </div>

                        <h2 class="title text-center" >Thức ăn vật nuôi</h2>
                        <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                @foreach($thucanthucung as $key=>$thucanthucung)

                                    <div class="item active ">

                                        <div class="col-sm-4">
                                            <div class="product-image-wrapper">
                                                <div class="single-products">
                                                    <div class="productinfo text-center">
                                                        <img src="/upload/product/{{$thucanthucung->product_image}}" alt="" height="250px" />
                                                        <h2>{{number_format($thucanthucung->product_price)}} VNĐ</h2>

                                                        <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>

                                                    </div>

                                                    <div class="product-overlay">
                                                        <div class="overlay-content">
                                                            <h2>{{number_format($thucanthucung->product_price)}} VNĐ</h2>
                                                            <p>{{$thucanthucung->product_name}}</p>
                                                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                            <div class="choose">
                                                <ul class="nav nav-pills nav-justified">
                                                    <li><a href="{{route('product.detail',['product_id'=>$thucanthucung->product_id])}}"><i class="fa fa-plus-square"></i>Chi Tiết</a></li>
                                                    <li><a href="#"><i class="fa fa-plus-square"></i>So sánh</a></li>
                                                </ul>
                                            </div>
                                        </div>

                                    </div>

                                @endforeach
                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/frontend/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

    <meta name="csrf-token" content="{{csrf_token()}}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | E-Shopper</title>
    <base href="{{asset('')}}">
    <link href="frontend/css/bootstrap.min.css" rel="stylesheet">
    <link href="frontend/css/font-awesome.min.css" rel="stylesheet">
    <link href="frontend/css/prettyPhoto.css" rel="stylesheet">
    <link href="frontend/css/price-range.css" rel="stylesheet">
    <link href="frontend/css/animate.css" rel="stylesheet">
	<link href="frontend/css/main.css" rel="stylesheet">
	<link href="frontend/css/responsive.css" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@9.17.2/dist/sweetalert2.min.css">



    <!--[if lt IE 9]>


    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="frontend/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="frontend/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="frontend/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="frontend/images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
	@include('frontend.header')

	@yield('content')

	@include('frontend.footer')



    <script src="frontend/js/jquery.js"></script>
	<script src="frontend/js/bootstrap.min.js"></script>
	<script src="frontend/js/jquery.scrollUp.min.js"></script>
	<script src="frontend/js/price-range.js"></script>
    <script src="frontend/js/jquery.prettyPhoto.js"></script>
    <script src="frontend/js/main.js"></script>
{{--    <script src="sweetalert2.all.min.js"></script>--}}
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    @yield('script')

<script type="text/javascript">
    $(document).ready(function () {
        $('.add-to-cart').click(function () {
            // Swal.fire('Any fool can use a computer');

        })
    })
</script>
</body>