routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layout');
});
//home login
Route::get('/admin','HomeController@index')->name('admin.index');

Route::post('/postLogin','HomeController@postLogin')->name('admin.postLogin');


Route::group(['prefix'=>'admin','as'=>'admin.','middleware' => 'checkLogin'], function(){



    Route::resource('/user','UserController');
    Route::resource('/slide','SlideController');
    Route::resource('/brand','BrandProductController');
    Route::resource('/product','ProductController');
    Route::resource('/category','CategoryController');
    Route::resource('/coupon','CouponController');

});

//frontend
//trang - chu
Route::get('/trang-chu','ShopController@index')->name('index');


Route::get('/category','ShopController@index')->name('category.index');
Route::get('/brand/{brand_slug}','ShopController@index')->name('brand.brand_slug');


Route::get('/category/{slug_category_product}','ShopController@show_category')->name('show_category');

Route::get('/trang-chu/chi-tiet/{product_id}','ShopController@detail_product')->name('product.detail');

Route::get('/danh-muc','ShopController@category')->name('home.category');
Route::get('/lien-he','ShopController@contact')->name('contact');
Route::get('/lien-he-voi-chung-toi','ShopController@postContact')->name('post.contact');

//shopping cart

Route::get('gio-hang','CartController@index')->name('cart.index');
Route::get('gio-hang/them-san-pham-gio-hang/{product_id}','CartController@addCart')->name('cart.add');
Route::delete('gio-hang/xoa-san-pham/{rowId}','CartController@removeCart')->name('cart.destroy');
Route::post('gio-hang/cap-nhap-gio-hang/','CartController@updateCart')->name('cart.update');
Route::get('gio-hang/tinh-ma-giam-gia','CartController@check_coupon')->name('check.coupon');

Route::post('gio-hang/cap-nhap-san-pham/','CartController@updateCart')->name('updateCart');

//Route::get('giohang','CartController@test')->name('cart');

app/Coupon.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Coupon extends Model
{
    public $timestamps = false;
        protected $fillable = [
        'coupon_name','coupon_time','coupon_condition','coupon_number','coupon_code'
    ];
    protected $primaryKey= 'coupon_id';
    protected $table = 'tbl_coupon';
}

app/Http/Controllers/CouponController.php
<?php

namespace App\Http\Controllers;

use App\Coupon;
use Illuminate\Http\Request;

class CouponController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Coupon::all();
//        $data1 = Coupon::latest()->paginate(2);

        return view('backend.coupon.index',[
            'data'=>$data,
//            'data1'=>$data1
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.coupon.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request ->validate([

        ],[

        ]);
        $coupon_name = $request->input('coupon_name');
        $coupon_time = $request->input('coupon_time');
        $coupon_condition = $request->input('coupon_condition');
        $coupon_number = $request->input('coupon_number');
        $coupon_code = $request->input('coupon_code');

        $coupon = new Coupon();
        $coupon -> coupon_name = $coupon_name;
        $coupon -> coupon_time = $coupon_time;
        $coupon -> coupon_condition = $coupon_condition;
        $coupon -> coupon_number = $coupon_number;
        $coupon -> coupon_code =$coupon_code;
        $coupon ->save();
        session()->flash('success','tạo thành công');
        return redirect()-> route('admin.coupon.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($coupon_id)
    {
        $edit = Coupon::find($coupon_id);
        return view('backend.coupon.edit',[
            'edit'=>$edit
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $coupon_id)
    {

        $coupon_name = $request->input('coupon_name');
        $coupon_time = $request->input('coupon_time');
        $coupon_condition = $request->input('coupon_condition');
        $coupon_number = $request->input('coupon_number');
        $coupon_code = $request->input('coupon_code');

        $coupon = Coupon::find($coupon_id);
        $coupon -> coupon_name = $coupon_name;
        $coupon -> coupon_time = $coupon_time;
        $coupon -> coupon_condition = $coupon_condition;
        $coupon -> coupon_number = $coupon_number;
        $coupon -> coupon_code =$coupon_code;
        $coupon ->save();
        session()->flash('success','cập nhập thành công');
        return redirect()-> route('admin.coupon.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($coupon_id)
    {
        $Delete = Coupon::destroy($coupon_id);

        if ($Delete) { // xóa thành công
            return response()->json(['success' => 1,'message'=>'Thành công']);
        } else {
            return response()->json(['success' => 0, 'message'=>'Thất bại']);
        }
    }
}

resources/views/backend/coupon/create.blade.php
@extends('backend.layout.main')
@section('content')
    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Thêm Mã Giảm Giá <a href="{{route('admin.coupon.index')}}" class="btn bg-purple "><i class="fa fa-plus"></i> Danh sách Mã Giảm Giá</a>

            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
                <li><a href="#"> Mã Giảm Giá </a></li>

            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">

                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Nhập thông tin Mã Giảm Giá</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->

                        <form role="form" action = "{{route('admin.coupon.store')}}" method = "post" enctype="multipart/form-data">
                            @csrf
                            <div class="box-body">
                                <div class="col-md-6">

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Tên mã giảm giá</label>
                                        <input data-validation="required"  data-validation-error-msg ="Điền tên mã giảm giá có ít nhất 1 ký tự"
                                               type="text" class="form-control" name="coupon_name" id="coupon_name"
                                               placeholder="Enter coupon_name">

                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Số lượng mã giảm giá</label>
                                        <input class="form-control" type="text" id="brand_slug" name="coupon_time" >


                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Tính năng mã</label>
                                        <select name = "coupon_condition" class="form-control input-sm m-bot15">
                                                <option value="0">----Chọn----</option>
                                                <option value="1">Giảm theo phần trăm</option>
                                                <option value="2">Giảm theo tiền</option>
                                        </select>

                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Nhập số % hoặc tiền giảm</label>
                                        <input class="form-control" type="text" id="brand_slug" name="coupon_number" >

                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Mã giảm giá</label>
                                        <input class="form-control" type="text" id="brand_slug" name="coupon_code" >


                                    </div>



                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox"> Check me out
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Thêm mã</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>

        </section>
        <!-- /.content -->
    </div>
@endsection
@section('scripts')
{{--    <script type="text/javascript">--}}


{{--        $('#brand_name').keyup(function(event) {--}}


{{--            var title, slug;--}}

{{--            //Lấy text từ thẻ input title --}}
{{--            title = document.getElementById("brand_name").value;--}}

{{--            //Đổi chữ hoa thành chữ thường--}}
{{--            slug = title.toLowerCase();--}}

{{--            //Đổi ký tự có dấu thành không dấu--}}
{{--            slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');--}}
{{--            slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');--}}
{{--            slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');--}}
{{--            slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');--}}
{{--            slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');--}}
{{--            slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');--}}
{{--            slug = slug.replace(/đ/gi, 'd');--}}
{{--            //Xóa các ký tự đặt biệt--}}
{{--            slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');--}}
{{--            //Đổi khoảng trắng thành ký tự gạch ngang--}}
{{--            slug = slug.replace(/ /gi, " - ");--}}
{{--            //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang--}}
{{--            //Phòng trường hợp người nhập vào quá nhiều ký tự trắng--}}
{{--            slug = slug.replace(/\-\-\-\-\-/gi, '-');--}}
{{--            slug = slug.replace(/\-\-\-\-/gi, '-');--}}
{{--            slug = slug.replace(/\-\-\-/gi, '-');--}}
{{--            slug = slug.replace(/\-\-/gi, '-');--}}
{{--            //Xóa các ký tự gạch ngang ở đầu và cuối--}}
{{--            slug = '@' + slug + '@';--}}
{{--            slug = slug.replace(/\@\-|\-\@|\@/gi, '');--}}
{{--            //In slug ra textbox có id “slug”--}}
{{--            $('#brand_slug').val(slug);--}}

{{--        });--}}
{{--    </script>--}}
@endsection

resources/views/backend/coupon/edit.blade.php
@extends('backend.layout.main')
@section('content')
    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Chỉnh Sửa Mã Giảm Giá <a href="{{route('admin.coupon.index')}}" class="btn bg-purple "><i class="fa fa-plus"></i> Danh sách Mã Giảm Giá</a>

            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
                <li><a href="#"> Mã Giảm Giá </a></li>

            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">

                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Nhập thông Tin Mã Giảm Giá Mới</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->

                        <form role="form" action = "{{route('admin.coupon.update',['coupon_id'=>$edit->coupon_id])}}" method = "post" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="box-body">
                                <div class="col-md-6">

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Tên mã giảm giá mới</label>
                                        <input value="{{$edit->coupon_name}}" data-validation="required"  data-validation-error-msg ="Điền tên mã giảm giá có ít nhất 1 ký tự"
                                               type="text" class="form-control" name="coupon_name" id="coupon_name"
                                               placeholder="Enter coupon_name">

                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Số lượng </label>
                                        <input value="{{$edit->coupon_time}}" class="form-control" type="text" id="brand_slug" name="coupon_time" >


                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Tính năng mã</label>
                                        <select  name = "coupon_condition" class="form-control input-sm m-bot15">
                                            <option value="0">----Chọn----</option>
                                            <option value="1">Giảm theo phần trăm</option>
                                            <option value="2">Giảm theo tiền</option>
                                        </select>

                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Nhập số % hoặc tiền giảm</label>
                                        <input value="{{$edit->coupon_number}}" class="form-control" type="text" id="brand_slug" name="coupon_number" >

                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Mã giảm giá mới</label>
                                        <input value="{{$edit->coupon_code}}" class="form-control" type="text" id="brand_slug" name="coupon_code" >


                                    </div>



                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox"> Check me out
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Câp nhập mã</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>

        </section>
        <!-- /.content -->
    </div>
@endsection
@section('scripts')
    {{--    <script type="text/javascript">--}}


    {{--        $('#brand_name').keyup(function(event) {--}}


    {{--            var title, slug;--}}

    {{--            //Lấy text từ thẻ input title --}}
    {{--            title = document.getElementById("brand_name").value;--}}

    {{--            //Đổi chữ hoa thành chữ thường--}}
    {{--            slug = title.toLowerCase();--}}

    {{--            //Đổi ký tự có dấu thành không dấu--}}
    {{--            slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');--}}
    {{--            slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');--}}
    {{--            slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');--}}
    {{--            slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');--}}
    {{--            slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');--}}
    {{--            slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');--}}
    {{--            slug = slug.replace(/đ/gi, 'd');--}}
    {{--            //Xóa các ký tự đặt biệt--}}
    {{--            slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');--}}
    {{--            //Đổi khoảng trắng thành ký tự gạch ngang--}}
    {{--            slug = slug.replace(/ /gi, " - ");--}}
    {{--            //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang--}}
    {{--            //Phòng trường hợp người nhập vào quá nhiều ký tự trắng--}}
    {{--            slug = slug.replace(/\-\-\-\-\-/gi, '-');--}}
    {{--            slug = slug.replace(/\-\-\-\-/gi, '-');--}}
    {{--            slug = slug.replace(/\-\-\-/gi, '-');--}}
    {{--            slug = slug.replace(/\-\-/gi, '-');--}}
    {{--            //Xóa các ký tự gạch ngang ở đầu và cuối--}}
    {{--            slug = '@' + slug + '@';--}}
    {{--            slug = slug.replace(/\@\-|\-\@|\@/gi, '');--}}
    {{--            //In slug ra textbox có id “slug”--}}
    {{--            $('#brand_slug').val(slug);--}}

    {{--        });--}}
    {{--    </script>--}}
@endsection

resources/views/backend/coupon/index.blade.php
@extends('backend.layout.main')
@section('content')
    <div class="content-wrapper">

        <section class="content-header">
            <h1>
                DANH SÁCH QUẢN LÝ MÃ GIẢM GIÁ <a href="{{route('admin.coupon.create')}}" class="btn bg-purple btn-flat"><i class="fa fa-plus"></i> Thêm MÃ </a>

            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-user"></i> QUẢN LÝ MÃ GIẢM GIÁ </a></li>
            </ol>
        </section>

        <section class="content">

            <div class="row">
                <div class="col-md-12">
                    <div class="box">

                        <div class="box-header with-border">

                            <h3 class="box-title">Danh Sách Các Mã</h3>

                        </div>
                        @if(session()->has('success'))
                            <div class="alert alert-success">{{session()->get('success')}}</div>
                        @endif


                        <div class="box-body">
                            <table class="table table-border">
                                <tbody>
                                <tr>
                                    <th style="width: 10px">STT</th>
                                    <th>coupon_name</th>
                                    <th>coupon_time</th>
                                    <th>coupon_condition</th>
                                    <th>coupon_number</th>
                                    <th>coupon_code</th>
                                    <th>Hành Động</th>
                                </tr>
                                @foreach($data as $key => $item)
                                    <tr class="item-{{ $item->coupon_id }}">
                                        <td>{{ $key +1}}</td>
                                        <td>{{ $item->coupon_name }}</td>
                                        <td>{{ $item->coupon_time }}</td>
                                        <td>{{ $item->coupon_condition }}</td>
                                        <td>{{ $item->coupon_number }}</td>
                                        <td>{{ $item->coupon_code }}</td>
                                        <td>
                                            <a  href="{{route('admin.coupon.edit',['coupon_id'=>$item->coupon_id])}}" class="btn btn-warning btn-edit"><i class="fa fa-pencil"></i></a>
                                            <button data-id="{{$item->coupon_id}}" class="btn btn-danger btn-delete"><i class="fa fa-trash"></i></button>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
{{--                        <div class="box-footer clearfix">--}}
{{--                            {{ $data->links()}}--}}
{{--                        </div>--}}
                    </div>
                </div>

            </div>


        </section>
        @endsection
        @section('my_js')
            <script type="text/javascript">
                $(document).ready(function() {
                    // Thiết lập csrf => chổng giả mạo
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN' : $('meta[name="csrf-token"]').attr('content')
                        }
                    })

                    $('.btn-delete').on('click',function () {

                        let id = $(this).data('id');

                        let result = confirm("Bạn có chắc chắn muốn xóa ?");

                        if (result) { // neu nhấn == ok , sẽ send request ajax

                            $.ajax({
                                url: '/admin/coupon/'+id,
                                type: 'DELETE', // phương truyền tải dữ liệu
                                data: {
                                    // dữ liệu truyền sang nếu có
                                    name : 'dung'
                                },
                                dataType: "json", // kiểu dữ liệu muốn nhận về
                                success: function (res) {

                                    if (res.success != 'undefined' && res.success == 1) { // xóa thành công
                                        $('.item-'+id).remove();
                                    }
                                    window.location.href = '/admin/coupon';
                                },
                                error: function (e) { // lỗi nếu có
                                    console.log(e);
                                }
                            });
                        }

                    });

                    /*$( ".btn-delete" ).click(function() {
                        alert( "Handler for .click() called." );
                    });*/

                });
            </script>
@endsection