routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layout');
});
//home login
Route::get('/admin','HomeController@index')->name('admin.index');

Route::post('/postLogin','HomeController@postLogin')->name('admin.postLogin');


Route::group(['prefix'=>'admin','as'=>'admin.','middleware' => 'checkLogin'], function(){



    Route::resource('/user','UserController');
    Route::resource('/slide','SlideController');
    Route::resource('/brand','BrandProductController');
    Route::resource('/product','ProductController');
    Route::resource('/category','CategoryController');
    Route::resource('/coupon','CouponController');

});

//frontend
//trang - chu
Route::get('/trang-chu','ShopController@index')->name('index');


Route::get('/category','ShopController@index')->name('category.index');
Route::get('/brand/{brand_slug}','ShopController@index')->name('brand.brand_slug');


Route::get('/category/{slug_category_product}','ShopController@show_category')->name('show_category');

Route::get('/trang-chu/chi-tiet/{product_id}','ShopController@detail_product')->name('product.detail');

Route::get('/danh-muc','ShopController@category')->name('home.category');
Route::get('/lien-he','ShopController@contact')->name('contact');
Route::get('/lien-he-voi-chung-toi','ShopController@postContact')->name('post.contact');

//shopping cart

Route::get('gio-hang','CartController@index')->name('cart.index');
Route::get('gio-hang/them-san-pham-gio-hang/{product_id}','CartController@addCart')->name('cart.add');
Route::delete('gio-hang/xoa-san-pham/{rowId}','CartController@removeCart')->name('cart.destroy');
Route::post('gio-hang/cap-nhap-gio-hang/','CartController@updateCart')->name('cart.update');
Route::get('gio-hang/tinh-ma-giam-gia','CartController@check_coupon')->name('check.coupon');

Route::post('gio-hang/cap-nhap-san-pham/','CartController@updateCart')->name('updateCart');

//Route::get('giohang','CartController@test')->name('cart');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\User;
use Session;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = User::all();

        $user = User::latest()->paginate(5);
        return view('backend.user.index',['data'=> $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $request -> validate(
            [
                'name'=>'required|max:255',
                'email'=>'required|email',
                'password'=>'required|min:6',
                'phone'=>'required',

            ],
            [
                'name.required' => 'bạn cần nhập họ tên',
                'email.email' => 'Email không được định dạng đúng',
                'password.required' =>'Vui lòng nhập mật khẩu',
                'password.min' =>'mật khẩu phải có 6 ký tự',
                'phone.required'=>'vui lòng nhập số điện thoại',


            ]);
        $admin_email = $request->input('email');
        $admin_password = $request->input('password');
        $admin_name = $request->input('name');
        $admin_phone = $request->input('phone');


        $user = new User();
        $user->email = $admin_email;
        $user->name = $admin_name;
        $user->password = bcrypt($admin_password);
        $user->phone = $admin_phone;

        $user->save();

        session()->flash('success','User create successfully.');

            return redirect()->route('admin.user.index')->with('thêm thành công');



    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit = User::find($id);
        return view('backend.user.edit',['edit' => $edit]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

            $admin_email = $request->input('email');
            $admin_password = $request->input('password');
            $admin_name = $request->input('name');
            $admin_phone = $request->input('phone');


            $user = User::find($id);
            $user->email = $admin_email;

            $user->password = bcrypt($admin_password);
            $user->name = $admin_name;
            $user->phone = $admin_phone;

            $user->save();

            session()->flash('success','User update successfully.');

                return redirect()->route('admin.user.index')->with('thêm thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $isDelete = User::destroy($id);

        if ($isDelete) { // xóa thành công
            return response()->json(['success' => 1,'message'=>'Thành công']);
        } else {
            return response()->json(['success' => 0, 'message'=>'Thất bại']);
        }

    }
}

resources/views/backend/user/create.blade.php
@extends('backend.layout.main')
@section('content')
<div class="content-wrapper">

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Thêm thông tin USER <a href="{{route('admin.user.index')}}" class="btn bg-purple "><i class="fa fa-plus"></i> Danh sách USER</a>
        
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">thêm thông tin USER</a></li>
        
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Nhập thông tin USER</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            
            <form role="form" action = "{{route('admin.user.store')}}" method = "post" enctype="multipart/form-data">
            @csrf
              <div class="box-body">
            <div class="col-md-6">
             
              <div class="form-group">
                  <label for="exampleInputEmail1">admin_email</label>
                  <input type="email" class="form-control" name="email" id="email" placeholder="Enter admin_email">
                  @if($errors->has('admin_email'))
                  <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px;color:red" >
                              <i class="fa fa-info"></i>{{$errors->first('admin_email')}}
                    </label>
                  @endif
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">admin_password </label>
                  <input type="password" class="form-control" name ="password " id="password " placeholder="Enter admin_password">
                  @if($errors->has('admin_password'))
                  <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px;color:red" >
                              <i class="fa fa-info"></i>{{$errors->first('admin_password')}}
                    </label>
                  @endif
                </div>
                

                <div class="form-group">
                  <label for="exampleInputPassword1">admin_name</label>
                  <input type="text" class="form-control" name ="name" id="name" placeholder="Enter admin_name">
                  @if($errors->has('name'))
                  <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px;color:red" >
                              <i class="fa fa-info"></i>{{$errors->first('name')}}
                    </label>
                  @endif
                </div>

                <div class="form-group"> 
                  <label for="exampleInputPassword1">admin_phone</label>
                  <input type="text" class="form-control" name ="phone" id="phone" placeholder="Enter admin_phone">
                  @if($errors->has('phone'))
                  <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px;color:red" >
                              <i class="fa fa-info"></i>{{$errors->first('phone')}}
                    </label>
                  @endif
                </div>
                
                <div class="checkbox">
                  <label>
                    <input type="checkbox" id="remember"> Check me out
                  </label>
                </div>
              </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
          <!-- /.box -->
        </div>
      </div>
      
    </section>
    <!-- /.content -->
  </div>
@endsection

resources/views/backend/user/edit.blade.php
@extends('backend.layout.main')
@section('content')
<div class="content-wrapper">

    <!-- Content Header  -->
    <section class="content-header">
      <h1>
        Sửa thông tin người dùng <a href="{{route('admin.user.index')}}" class="btn bg-purple "><i class="fa fa-plus"></i> Danh sách người dùng</a>
        
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Sửa thông tin người dùng</a></li>
        
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Nhập thông tin người dùng</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form"  action="{{route('admin.user.update',['id'=> $edit->id])}}" method="post" enctype="multipart/form-data">
              @csrf
              @method('PUT')
              <div class="box-body">
            <div class="col-md-6">
              
                <div class="form-group">
                  <label for="exampleInputEmail1">Email </label>
                  <input value="{{$edit->email}}" type="email" class="form-control" name ="email" id="email" placeholder="Enter email">
                  @if($errors->has('email'))
                  <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px;color:red" >
                              <i class="fa fa-info"></i>{{$errors->first('email')}}
                    </label>
                  @endif
                </div>
                <div class="form-group">
                  <label for="exampleInputPassword1">Password</label>
                  <input value="{{$edit->password}}" type="password" class="form-control" name ="password" id="password" placeholder="Enter Password">
                  @if($errors->has('password'))
                  <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px;color:red" >
                              <i class="fa fa-info"></i>{{$errors->first('password')}}
                    </label>
                  @endif
                </div>

                <div class="form-group">
                  <label for="exampleInputEmail1">Name</label>
                  <input value="{{$edit->name}}" type="text" class="form-control" name="name" id="name" placeholder="Enter full_name">
                  @if($errors->has('name'))
                  <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px;color:red" >
                              <i class="fa fa-info"></i>{{$errors->first('name')}}
                    </label>
                  @endif
                </div>

                <div class="form-group">
                  <label for="exampleInputPassword1">Phone</label>
                  <input value="{{$edit->phone}}" type="number" class="form-control" name ="phone" id="phone" placeholder="Enter phone">
                  @if($errors->has('phone'))
                  <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px;color:red" >
                              <i class="fa fa-info"></i>{{$errors->first('phone')}}
                    </label>
                  @endif
                </div>

                
                
                <div class="checkbox">
                  <label>
                    <input type="checkbox"> Check me out
                  </label>
                </div>
              </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Update</button>
              </div>
            </form>
          </div>
          <!-- /.box -->
        </div>
      </div>
      
    </section>
    <!-- /.content -->
  </div>
@endsection

resources/views/backend/user/index.blade.php
@extends('backend.layout.main')
@section('content')
<div class="content-wrapper">

    <section class="content-header">
      <h1>
        DANH SÁCH QUẢN LÝ USER <a href="{{route('admin.user.create')}}" class="btn bg-purple btn-flat"><i class="fa fa-plus"></i> Thêm</a>

      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-user"></i> QUẢN LÝ USER </a></li>
      </ol>
    </section>

<section class="content">

     <div class="row">
       <div class="col-md-12">
         <div class="box">

            <div class="box-header with-border">

              <h3 class="box-title">Danh Sách USER</h3>

            </div>
            @if(session()->has('success'))
              <div class="alert alert-success">{{session()->get('success')}}</div>
            @endif


            <div class="box-body">
                <table class="table table-border">
                  <tbody>
                            <tr>
                                <th style="width: 10px">STT</th>
                                <th>admin_email</th>
                                <th>admin_password</th>
                                <th>admin_name</th>
                                <th>admin_phone</th>

                                <th>Hành Động</th>
                            </tr>
                          @foreach($data as $key => $item)
                            <tr class="item-{{ $item->id }}">
                                <td>{{ $key +1}}</td>
                                <td>{{ $item->email }}</td>
                                <td>{{ $item->password }}</td>
                                <td>{{ $item->name }}</td>
                                <td>{{ $item->phone }}</td>


                                <td>

                                  <a  href="{{route('admin.user.edit',['edit'=>$item->id])}}" class="btn btn-warning btn-edit"><i class="fa fa-pencil"></i></a>
                                   <button data-id="{{$item->id}}" class="btn btn-danger btn-delete"><i class="fa fa-trash"></i></button>
                                </td>
                            </tr>
                            @endforeach
                  </tbody>
                </table>
            </div>
         </div>
       </div>

     </div>


    </section>
@endsection
@section('my_js')
<script type="text/javascript">
        $(document).ready(function() {
            // Thiết lập csrf => chổng giả mạo
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN' : $('meta[name="csrf-token"]').attr('content')
                }
            })

            $('.btn-delete').on('click',function () {

                let id = $(this).data('id');

                let result = confirm("Bạn có chắc chắn muốn xóa ?");

                if (result) { // neu nhấn == ok , sẽ send request ajax

                    $.ajax({
                        url: '/admin/user/'+id, // http://webthucpham.local:8888/user/8
                        type: 'DELETE', // phương truyền tải dữ liệu
                        data: {
                            // dữ liệu truyền sang nếu có
                            name : 'dung'
                        },
                        dataType: "json", // kiểu dữ liệu muốn nhận về
                        success: function (res) {

                            if (res.success != 'undefined' && res.success == 1) { // xóa thành công
                                $('.item-'+id).remove();
                            }
                            window.location.href = '/admin/user';
                        },
                        error: function (e) { // lỗi nếu có
                            console.log(e);
                        }
                    });
                }

            });

            /*$( ".btn-delete" ).click(function() {
                alert( "Handler for .click() called." );
            });*/

        });
    </script>
@endsection